name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate github-contribution-grid-snake
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: akshay-k-a-dev
          outputs: |
            ./dist/snake.svg

      - name: push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
